### ISSUE TITLE
How can I solve problems with UTF-8 encoding

### ISSUE THREAD

**Issue by mwigham** [polifonia-project/sparql-anything-cookbook#7]
I have a csv file in UTF-8 format that contains special characters. When I SPARQL Anything the csv, then the special characters are messed up in the output. 

E.g. "Martín Gómez-Ullate" becomes "Mart├¡n G├│mez-Ullate"

According to the documentation, the default output is UTF-8, so this should work ok. Could you tell me  how I can solve this problem please?

**Comment by enridaga** [comment]
Maybe the source file is not utf8? Check the charset config from the documentation.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: mwigham ***@***.***>
Sent: Thursday, September 22, 2022 3:41:29 PM
To: polifonia-project/sparql-anything-cookbook ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [polifonia-project/sparql-anything-cookbook] How can I solve problems with UTF-8 encoding (Issue #7)


I have a csv file in UTF-8 format that contains special characters. When I SPARQL Anything the csv, then the special characters are messed up in the output.

E.g. "Martín Gómez-Ullate" becomes "Mart├¡n G├│mez-Ullate"

According to the documentation, the default output is UTF-8, so this should work ok. Could you tell me how I can solve this problem please?

**Comment by mwigham** [comment]
According to Notepad++ it was UTF-8, but saving the file again explicitly as UTF-8 solved the problem, thank you!
